; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32@6.13.0
board = esp32-s3-devkitc-1
framework = espidf, arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.filesystem = spiffs
board_build.partitions = partitions.csv

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17

    ; 공유 폴더의 절대 경로를 컴포넌트 검색 경로에 추가
    ;-I D:/_MyProjects/esp_shared_components/arduino/cores/esp32

    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -I include

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.12
    bblanchon/ArduinoJson @ ^6.21.5
    knolleary/PubSubClient @ ^2.8.0
