[env:esp32-s3-devkitc-1]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32-s3-devkitc-1
framework = espidf, arduino

platform_packages =
    ; ESP-IDF 5.1.2 프레임워크 (이미 설치됨)
    framework-espidf @ ~3.50102.0
    ; Arduino 3.0.1 컴포넌트 (이미 설치됨)
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.1
    ; [검증됨] ESP-IDF 5.1 전용 GCC 12.2.0 툴체인 명칭 수정
    toolchain-xtensa-esp32s3 @ 12.2.0+20230208
    toolchain-riscv32-esp @ 12.2.0+20230208

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs

build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3
    -DINC_ENABLE_CLOUD
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_CACHE_WORKAROUND
    -I include
; 추가: 포맷 경고 및 클래스 메모리 접근 경고를 에러로 처리하지 않음
    -Wno-error=format=
    -Wno-error=class-memaccess
    -Wno-format
    -Wno-unused-variable
    -Wno-unused-but-set-variable    
         
lib_deps =
    lovyan03/LovyanGFX @ ^1.1.12
    bblanchon/ArduinoJson @ ^6.21.5